### ISSUE TITLE
Why not use gitbook?

### ISSUE THREAD

**Issue by djyde** [ruanyf/jstraining#10]
I think using gitbook to publish it is better.

**Comment by ruanyf** [comment]
There is no way of displaying and downloading `demos`  in Gitbook.

**Comment by djyde** [comment]
Why? Is it not just a link to demo's files?

For example:

> 打开 [demos/backbone-demo/index.html](https://github.com/ruanyf/jstraining/blob/master/demos/backbone-demo/index.html)，按照《操作说明》，查看示例。

**Comment by ruanyf** [comment]
The docs are intended for ppt, not for a book.
