### ISSUE TITLE
mobx-demo 无法运行

### ISSUE THREAD

**Issue by jueduizone** [ruanyf/jstraining#11]
阮老师，您好，我这边运行mobx-demo这个例子时候出现了以下问题，npm intsall后，``eslint-config-airbnb@13.0.0``依赖无法安装报错：
```
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-import@^2.1.0 but none was installed.
```
目前这个问题已被解决，需要手动安装`eslint-plugin-jsx-a11`和`eslint-plugin-import`且制定版本号：
`npm install --save-dev eslint-plugin-jsx-a11y@^2.2.3 eslint-plugin-import@^2.1.0`
之后再install就好了。intstall后显示：
```
npm WARN mobx-demo@1.0.0 No description
npm WARN mobx-demo@1.0.0 No repository field.
```
这时候去`npm start`没有报错且自动打开浏览器，但是无法访问，Chrome提示：localhost 网页无法正常运作，请问大概哪里出了问题？
node版本：v6.9.1，npm版本：3.10.8

**Comment by ruanyf** [comment]
我修改过了，你重新拉一下代码，然后重新安装，应该不会有问题了。

**Comment by jueduizone** [comment]
阮老师，现在install后没有那些报错了，只有：
```
npm WARN mobx-demo@1.0.0 No description
npm WARN mobx-demo@1.0.0 No repository field.
```
这些提示，然后start后很快就启动了，最后的提示：
```
webpack: bundle is now VALID.
```
但是浏览器打开访问`http://localhost:8080/`还是报错：
localhost 网页无法正常运作
localhost 未发送任何数据。

**Comment by ruanyf** [comment]
我这里是好的。你要不把 node_modules 目录删掉，从头再来一次。
