### ISSUE TITLE
关于未来只有两种工程师这种说法有个疑问？

### ISSUE THREAD

**Issue by andy-zhangtao** [ruanyf/jstraining#12]
在第一讲最后一节中，提到
```
未来只有两种软件工程师

端工程师
手机端
PC 端
TV 端
VR 端
……
云工程师
```
这里有个疑问？  那么写golang高并发的工程师，写java处理业务的工程师, 写内核虚拟化的工程师，或者写db数据库的工程师应该归到哪一类呢？

按照文中的分类，前端必然不属于。 后端？ 貌似也不属于。因为可能不会与UI，数据库进行交互。

PC、TV、VR也不沾边。  

云工程师？ 范围有点太广。内核虚拟化和云无关，但要实现云，虚拟化有是一个非常好的选择。 所以看到这里，迷茫了！

**Comment by ruanyf** [comment]
这是我个人的猜想。

云工程师就是后端服务化。只要做的是后端服务，就是云工程师，不用纠结哪种语言。
