### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by liu2010y** [ruanyf/jstraining#17]
我在做mobx-demo时 npm install 后提示错误：
>npm ERR! Windows_NT 6.1.7601
>npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program >Files\\nodejs\\node_modules\\npm\\bin\
>\npm-cli.js" "install"
>npm ERR! node v4.4.7
>npm ERR! npm  v2.15.8
>npm ERR! code EPEERINVALID
>npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@3.0.1 does not satisfy its siblings' peerDepend
>encies requirements!
>npm ERR! peerinvalid Peer eslint-config-airbnb@13.0.0 wants eslint-plugin-jsx-a11y@^2.2.3
>
>npm ERR! Please include the following file with any support request:
>npm ERR!    mypath\demos\mobx-demo\npm-debug.log

**Comment by liu2010y** [comment]
求各位师傅指点下迷津，感激不尽

**Comment by qmkCamel** [comment]
升级一下node

**Comment by liu2010y** [comment]
我用nvm 下载了最新版的，切换的时候报错：
xxx\jstraining\demos\express-demo>nvm list
    7.1.0
  * 4.4.7 (Currently using 64-bit executable)
xxx\jstraining\demos\express-demo>nvm use 7.1.0
exit status 1: 'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by qmkCamel** [comment]
windows 是区分32bit和64bit的，你下载对了么 
看下官网你就知道了

**Comment by fuchao2012** [comment]
windows 下编写建议使用 cmder/babun 做一个类 Linux 环境，否则类似问题会源源不断。

PS. 开发中涉及到的软件，node/python/ruby 等用安装包安装的软件，建议初学者统一 **安装在默认路径 ** 。

**Comment by ruanyf** [comment]
不好意思，原来的库代码因为依赖升级，导致不兼容报错。我上个星期已经修掉这个问题了。https://github.com/ruanyf/jstraining/issues/11

你再拉一下代码，然后删掉 node_modules 目录，重新安装试试。

**Comment by liu2010y** [comment]
好的，谢谢大家
