### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by orchestor** [ruanyf/jstraining#23]
Python编程背景，花了一下午走完了所有流程。想问一下，有没有更深入和完整的例子参考？Thanks

**Comment by ruanyf** [comment]
所有例子都是入门级，只用来指明方向。

**Comment by ruanyf** [comment]
对哪个主题感兴趣，在 Google 搜索 “xxxx tutorial”就可以了。

**Comment by orchestor** [comment]
谢谢。因为信息太多噪音，参考问问你们经历过的高质量的项目。 好在JS这条路径继续学习下去。
