### ISSUE TITLE
git commit 出错

### ISSUE THREAD

**Issue by monster-gump** [ruanyf/jstraining#24]
阮老师您好，我在自己的分支上修改完想 commit 的时候 node 报错，查了一下相关的问题还是不清楚应该怎么解决，想请教一下您，打扰了。
目前进度：刚完成 react 的部分，其中两个需要 npm install 的练习都已完成
报错信息：
```bash
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10

npm ERR! missing script: lint
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
我看到有其他 issue  也是类似的 比如 [issue ](https://github.com/npm/npm/issues/13637)
可是我没弄懂这个 lint 的 script 该加到哪里去，是哪一个 package.json 文件？而其内容又需要怎么写呢？
比如我尝试修改 /usr/local/lib/node_modules/npm 下的 package.json 文件，不过有点一脸懵逼=。=
```bash
"scripts": {
    "lint": "eslint *.js",  #此处是我修改的，但似乎没有效果
    "dumpconf": "env | grep npm | sort | uniq",
    "prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc",
    "preversion": "bash scripts/update-authors.sh && git add AUTHORS && git commit -m \"update AUTHORS\" || true",
    "tap": "tap --timeout 300",
    "tap-cover": "tap --coverage --timeout 600",
    "test": "standard && npm run test-tap",
    "test-coverage": "npm run tap-cover -- \"test/tap/*.js\" \"test/network/*.js\" \"test/slow/*.js\" \"test/broken-under-*/*.js\"",
    "test-tap": "npm run tap -- \"test/tap/*.js\" \"test/network/*.js\" \"test/slow/*.js\" \"test/broken-under-*/*.js\"",
    "test-node": "\"$NODE\" \"node_modules/.bin/tap\" --timeout 240 \"test/tap/*.js\" \"test/network/*.js\" \"test/slow/*.js\" \"test/broken-under-nyc*/*.js\""
  },
  "license": "Artistic-2.0"
}
```

参考了一下 npm 那边的 [issue](https://github.com/npm/npm/issues/14309) 反而更加疑惑了：jstraning 本身下面是空的，为何又会导致这样的问题呢
我是在 jstraning 目录下 git commit 的，然而这个文件夹下本身是没有 npm 相关的东西吧，至少我跑 npm run 和 npm start 时输出是
```bash
# npm run
Lifecycle scripts included in monster:
  test
    echo "Error: no test specified" && exit 1

# npm start 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10

npm ERR! missing script: start
```
所以终极困惑还是，为什么此处无法成功 git commit _(:з」∠)_

**Comment by fuchao2012** [comment]
npm run  是一体的  run 后边跟着你 package.json 文件里 scirpt 底下的 指令。例如

```
$ npm run test
$ npm run dev
$ npm run build
```

另外，package.json 是你的 `项目根目录` 不是系统目录，比如

```
# 你新建了一个项目叫做 test-npm， 并在里面初始化你的 package.json（或者自己手写一个）
$ mkdir test-npm && cd $_
$ npm init
```
此刻打开你喜欢的编辑器，就能在这个目录下找到 `package.json`了

---

冒昧作答，请 @ruanyf 大大指正（：

**Comment by monster-gump** [comment]
@fuchao2012 
这点我就觉得很迷 项目根目录是 jstraining 的话，哪来的 package.json 呢?

**Comment by Aladdin-ADD** [comment]
首先，commit默认是不会执行lint的，除非你使用了git hooks (http://gitbook.liuhui998.com/5_8.html)。
一般情况下，如果你没有手动修改这些文件，很有可能是某些npm修改了它(eg. https://www.npmjs.com/package/pre-commit)，因为git hooks位于.git目录，不会提交到git仓库，所以别人不会复现你的问题。
解决方案：

- 删除.git/hooks目录下所有文件

- 最暴力的方法，删除`.git`目录，然后重新执行`git init`（这样你所有的提交历史都会丢失）

**Comment by ruanyf** [comment]
把`.git/hooks`目录下的所有文件都删掉。
