### ISSUE TITLE
并没有前后端不分的时代，只有分不清前后端的时代。

### ISSUE THREAD

**Issue by calidion** [ruanyf/jstraining#26]
前后端从没有混合过。

怎么会有前后端不分的时代？

内容还是自相矛盾了。

前后端分离之说可以终止了。

**Comment by calidion** [comment]
上一节的内容是：

```
前端：针对浏览器的开发，代码在浏览器运行
后端：针对服务器的开发，代码在服务器运行
```

下一节的内容是

```
前后端不分的时代

互联网发展的早期，前后端开发是一体的，前端代码是后端代码的一部分。

后端收到浏览器的请求
生成静态页面
发送到浏览器
```

首先，前后端与前后端代码是两回事。
其次，前后端与前后端开发者是两回事。
前端代码在浏览器执行的ＪＳ，HTML，CSS。后端代码是在后端执行的ＪＳ，ＨＴＭＬ，ＣＳＳ或者其它的代码。
前端工程师可以做后端代码的开发区，后端工程师也可以做前端代码的开发。

如果前后端熟悉程度都很高，就是一个合格的全栈。

麻烦先自己搞明白了，不要误导他人。

**Comment by ruanyf** [comment]
谢谢您的意见。
