### ISSUE TITLE
Nightmare测试taobao的.wait('#spulist-grid')超时

### ISSUE THREAD

**Issue by zyzhan2015** [ruanyf/jstraining#27]
`$ node taobao.test.js`
CMD提示：
`Search failed: Error: .wait() timed out after 30000msec`
弹出的electron窗口中进入搜索页以后不显示结果

**Comment by ruanyf** [comment]
我改过了，你再拉一下代码，运行试试看。

**Comment by zyzhan2015** [comment]
`Search failed: Cannot read property 'textContent' of null`

**Comment by ruanyf** [comment]
你没有取到 DOM，有文件加载不成功，应该是你的文档问题。

我这里是可以成功的，即使没有修改也可以成本。

**Comment by zyzhan2015** [comment]
好的

**Comment by Tyno945** [comment]
我也遇到这个问题了，无法解决，自己去淘宝网搜索正常的
