### ISSUE TITLE
 MobX 框架那节，按照《操作说明》执行npm install会报错。

### ISSUE THREAD

**Issue by frankwang0909** [ruanyf/jstraining#28]
报错信息如下：
![qq 20170119162142](https://cloud.githubusercontent.com/assets/17450638/22098837/7f87d5a8-de63-11e6-96d3-61680cb8dd4c.png)

根据报错信息，版本依赖有冲突，需要修改package.json里的41行，改为"eslint-plugin-import": "^2.2.0",

**Comment by frankwang0909** [comment]
Redux 架构那节也是，执行npm install会报错，报错提示同上，解决方法同上。当然也可以改成："eslint-plugin-import": "latest",

**Comment by ruanyf** [comment]
那两个 demo 用了脚手架，本身用不到eslint，我已经删除了依赖。

你更新一下源码，然后重新安装依赖即可。
