### ISSUE TITLE
安装nightmare依赖出现问题

### ISSUE THREAD

**Issue by Sortinn** [ruanyf/jstraining#49]
我使用Electron官网提供的安装方法：

> $ npm install --save-dev electron

执行之后，安装停留在node install.js下，如下：
<img width="918" alt="2017-10-13 7 22 29" src="https://user-images.githubusercontent.com/23185249/31544276-a5288728-afdf-11e7-9e56-946472127ff1.png">
`ctrl` + `c`退出后，运行:
> $ node taobao.test.js

会抛出electron安装失败的错误：
<img width="881" alt="2017-10-13 7 34 42" src="https://user-images.githubusercontent.com/23185249/31544485-a50f4f14-afe0-11e7-9807-a2c57b35218a.png">
我在想是不是`jstraining/demos/nightmare-demo/node_modules/electron/install.js`这个文件的问题，可是我并不是很懂这个文件的描述的具体内容。
我很想知道问题出在哪里，所以过来寻求您的指点。非常感谢。

**Comment by ruanyf** [comment]
设置 ELECTRON_MIRROR 变量试试看。

https://github.com/ruanyf/jstraining/blob/master/demos/README.md#nightmare

**Comment by Sortinn** [comment]
非常感谢您的回复！可是我在设置完之后仍然存在相同的问题。其实最开始我已经按照您的方法设置了ELECTRON_MIRROR 变量，由于出现安装不成功的提示，所以我换了官方提供的方式安装Electron。这次我删除了安装的依赖，重新按照您的方法进行安装，可是问题依然存在，并且出现了如下的报错：

<img width="1295" alt="2017-10-15 9 14 30" src="https://user-images.githubusercontent.com/23185249/31580660-55b87836-b11c-11e7-9833-1212d090a4ad.png">

安装中首次出现错误（5976）的部分日志如下：

<img width="1021" alt="2017-10-15 9 22 38" src="https://user-images.githubusercontent.com/23185249/31580707-90be9522-b11d-11e7-891d-e512088459a1.png">

期待得到您的回复，谢谢！
