### ISSUE TITLE
那么前端工程师的未来在哪

### ISSUE THREAD

**Issue by Hancoson** [ruanyf/jstraining#51]
30岁后，40岁后……作为前端应该往什么方向发展？

**Comment by ruanyf** [comment]
UI 层的工作，比较适合年轻人。

现在的 UI 工程师，应该完善自己的技能，逐步转向其他领域。

**Comment by shaohailong** [comment]
转向哪些领域呢，后台开发，还是管理，还是什么呢。

发自我的 iPhone

**Comment by ruanyf** [comment]
可以转向那些更强调积累、要求深层次技能、技术更稳定的领域，比如底层开发和 AI 都是。但也不一定，还是看每个人的具体情况。

**Comment by giantss** [comment]
我最开始是做javaEE出生的，做了一年，发现H5很火就开始搞移动端跨平台开发，使用过appcan，cordova+sencha touch做过两个线上都app，写过php后台，由于android上性能瓶颈，现在在做react native 开发，总之前端的发展变化真的太快了，我现在这种方向是否稳定啊 @ruanyf

**Comment by wamm521** [comment]
现在自己26岁，已经做了3年前端开发 ，每天巩固基础，学习使用各种前端框架。也想过30岁我还做前端吗？可能会偏产品一些。自己也写博客，想也帮助别人解决技术问题

**Comment by ruanyf** [comment]
@giantss 如果能够适合技术栈的变化，这样做下去没问题啊。

有些人不适应前端技术栈的快速变化，这时可以考虑转领域。

**Comment by giantss** [comment]
因为我一直在创业公司工作，所以方方面面都能接触到，所以我我感觉学一门新的技术或者框架是很有趣的，😁。

**Comment by shaohailong** [comment]
老铁. 你博客地址是什么啊. 去拜访拜访.


开 23 November 2017 在 11:40:34 AM, wamm521 (notifications@github.com) 写到:

现在自己26岁，已经做了3年前端开发 ，每天巩固基础，学习使用各种前端框架。也想过30岁我还做前端吗？可能会偏产品一些。自己也写博客，想也帮助别人解决技术问题
