### ISSUE TITLE
Assertion failed: frame_header.payload_length == sizeof xfer_info, file src\win\pipe.c

### ISSUE THREAD

**Issue by countBunny** [ruanyf/jstraining#55]
> mocha -t 15000 ./react/test.js

  test app.html
Assertion failed: frame_header.payload_length == sizeof xfer_info, file src\win\pipe.c, line 1708e
src\win\pipe.c, line 1708
npm ERR! code ELIFECYCLE
Assertion failed: frame_header.payload_length == sizeof xfer_info, fils`f x
fer_info, file src\win\pipe.c, line 1708
npm ERR! code ELIFECYCLE                                                                    above.
npm ERR! errno 3221226505                             0 ./react/test.jtional logging outputnpm ERR! establish_node@1.0.0 test-app: `mocha -t 1500
Assertion failed: frame_header.payload_length == sizeof xfer_info, file src\win\pipe.c, line 1708xfer_info, file src\win\pipe.c, line 1708
npm ERR! code ELIFECYCLEnpm ERR! errno 3221226505                               ./react/test.js`npm ERR! establish_node@1.0.0 test-app: `mocha -t 15000./react/test.js`
npm ERR! Exit status 3221226505                         ipt.npm ERR!                                                is likely additional logging output above.npm ERR! Failed at the establish_node@1.0.0 test-app script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

缴枪了老师，搞不定这个···nightmare的就抛这个

**Comment by ruanyf** [comment]
这是教程里面的哪一个 demo？
