### ISSUE TITLE
使用postman发送请求时的问题

### ISSUE THREAD

**Issue by RuinousCheng** [ruanyf/jstraining#56]
在按照demo中的文档进行REST API 实验时，有几个问题：
**1.  POST 请求中，如何让postID传递的是数字而不是字符串**
    我在key中填 postID ,value 中填 1，最后get到的数据会是 一个字符串。
**2. delete 请求得到的结果与预期的会不一样。**
    在POST了多条数据后（postID不同），发送 DELETE 请求，删除的数据总是比我预期的多，那么这里的删除规则是什么？

**Comment by RuinousCheng** [comment]
另外，postman 作为扩展程序安装到chrome中无法正常使用，我使用的是官网下载的postman APP。

**Comment by ruanyf** [comment]
可能是 JSON Server 和 Postman 升级的原因，我现在没时间改。

你可以参考 JSON Server 本身的文档，用 curl 来做练习。
https://github.com/typicode/json-server

**Comment by RuinousCheng** [comment]
delete 结果与预期不符的原因是JSON Server 本身的问题，JSON Server的issue中有挺多问这个的，也有一个pull request 提交了相关解决方案，不过与main branch有冲突，没有被采纳
