### ISSUE TITLE
请教闭包问题

### ISSUE THREAD

**Issue by Panamer** [ruanyf/jstraining#60]
老师：
如果内部函数没有引用外部函数作用域的变量，算是闭包吗
把内部函数从 匿名函数 换为 函数表达式  然后它还是闭包吗

**Comment by ruanyf** [comment]
抱歉，这是代码库，不是答疑库。

**Comment by ZeitgeistBaby** [comment]
既然看到这封邮件，就说一下我理解的吧。我看到资料是这么说的：函数内部，但凡是内部的函数被保存到外部，它一定生成闭包（有值被return出去，形成闭包），也就是说，内部变量只要被保存到外部则形成闭包。我理解的是，因为作用域的关系，函数内部的值不能被外部使用，所以用闭包来储存值，你问的问题，1.“内部没有引用外部作用域变量”，是说自己调用自己的变量吗？这跟闭包有关系？
2，“ 把内部函数从 匿名函数 换为 函数表达式 然后它还是闭包吗
”，看你把这个函数用来干嘛了，这个函数表达式如果将内部值引用保存后，接着函数拿出去被外部使用就是闭包。使用闭包，是有一定目的性的，而闭包的几大作用，你可以查阅一下资料。以上如有错误，烦请指正。

郭永威 <notifications@github.com> 于2018年12月10日周一 下午7:33写道：
