### ISSUE TITLE
mobx-demo/redux-demo 无法运行

### ISSUE THREAD

**Issue by iwinstar1980** [ruanyf/jstraining#62]
npm start 执行的时候抛出下面的错误信息，初学者，实在是看不明白

> mobx-demo@1.0.0 start H:\Python\JS\jstraining\demos\mobx-demo
> webpack-dev-server --devtool eval --progress --hot --content-base app
                                                                                                   70% 1/1 build modulesevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1260:19)
    at listenInCluster (net.js:1325:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1458:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobx-demo@1.0.0 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mobx-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by iwinstar1980** [comment]
redux-demo执行 npm start的时候抛出的错误信息

> redux-demo@1.0.0 start H:\Python\JS\jstraining\demos\redux-demo
> webpack-dev-server --devtool eval --progress --hot --content-base app
                                                                                                   70% 1/1 build modulesevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1260:19)
    at listenInCluster (net.js:1325:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1458:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-demo@1.0.0 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ruanyf** [comment]
目录没权限报错，Windows 系统不熟悉。你以 Administrator 的身份运行试试看。

**Comment by iwinstar1980** [comment]
用管理员权限启动cmd，执行npm start 还是不行

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\U577288\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.8.0
3 info using node@v10.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mobx-demo@1.0.0~prestart: mobx-demo@1.0.0
6 info lifecycle mobx-demo@1.0.0~start: mobx-demo@1.0.0
7 verbose lifecycle mobx-demo@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle mobx-demo@1.0.0~start: PATH: C:\Users\U577288\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Python\JS\jstraining\demos\mobx-demo\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Java\jdk1.8.0_201\bin;C:\Java\jdk1.8.0_201\jre\bin;C:\apache-maven-3.6.0\bin;C:\Program Files\PowerShell\6\;C:\Program Files\nodejs\;C:\Python37\Scripts\;C:\Python37\;C:\Users\U577288\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm 2018.3.2\bin;C:\Users\U577288\AppData\Roaming\npm
9 verbose lifecycle mobx-demo@1.0.0~start: CWD: H:\Python\JS\jstraining\demos\mobx-demo
10 silly lifecycle mobx-demo@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'webpack-dev-server --devtool eval --progress --hot --content-base app' ]
11 silly lifecycle mobx-demo@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle mobx-demo@1.0.0~start: Failed to exec start script
13 verbose stack Error: mobx-demo@1.0.0 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\U577288\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\U577288\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mobx-demo@1.0.0
15 verbose cwd H:\Python\JS\jstraining\demos\mobx-demo
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\U577288\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.1
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error mobx-demo@1.0.0 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
22 error Exit status 1
23 error Failed at the mobx-demo@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ruanyf** [comment]
Mac 下面是正常的。

你删掉 node_modules 目录，用管理员身份重新安装依赖`npm install`试试看。

**Comment by iwinstar1980** [comment]
重新执行 npm install之后的结果信息如下，然后再执行 npm start 还是一样的错误

npm install
npm WARN copy-webpack-plugin@5.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-demo@1.0.0 No description
npm WARN mobx-demo@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 704 packages from 585 contributors and audited 5124 packages in 75.049s
found 5 vulnerabilities (2 low, 1 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by iwinstar1980** [comment]
看上面给出的信息应该是操作系统不支持，导致fsevents这个包没有安装成功导致的

**Comment by ruanyf** [comment]
copy-webpack-plugin 这个插件需要 Webpack 4.x。目前，没时间修这个问题。

建议在其他操作系统上运行这个 demo。

**Comment by iwinstar1980** [comment]
好的，我装个虚拟机试一下，可能的话，希望您有时间的时候能够修复这个问题
