### ISSUE TITLE
react-component-demo 在浏览器运行控制台报错

### ISSUE THREAD

**Issue by DaiZhaoedu** [ruanyf/jstraining#63]
阮老师请问 为什么文件找不到？该如何解决
react.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
react-dom.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
babel.min.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by ruanyf** [comment]
不知道你怎么打开的，都在同一个目录下面。
